Repository Next-Flip/Momentum-Apps, pull requests merged in 2024-11, with the labels that each got.

#30 Added Yapper + Highscores to Flappy Bird
  flappy_bird/application.fam
  flappy_bird/assets/yapper_01.png
  flappy_bird/assets/yapper_02.png
  flappy_bird/assets/yapper_03.png
  flappy_bird/flappy_bird.c
Labels: feature

#32 Unload assetpacks flag
  mfkey/application.fam
  mp_flipper/application.fam
Labels: enhancement

#31 [Flappy Bird] Updates
  flappy_bird/application.fam
  flappy_bird/assets/yappyghost_01.png
  flappy_bird/assets/yappyghost_02.png
  flappy_bird/assets/yappyghost_03.png
  flappy_bird/flappy_bird.c
Labels: enhancement

#35 ESP Flasher: add c3 and c6 to s3 option
  esp_flasher/application.fam
  esp_flasher/scenes/esp_flasher_scene_browse.c
Labels: bugfix
